name: gradr_lib
description: Convert climbing grading systems with a really simple interface.
version: 0.0.1
homepage: https://github.com/gradr-dev/gradr_lib

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
